d /run/a4diag-target 0750 root a4diag-target -
d /var/lib/a4diag-target 0750 root a4diag-target -
d /var/lib/a4diag-target/executor 0700 root root -
d /var/lib/a4diag-target/.ssh 0700 a4diag-target a4diag-target -
